name: LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update LeetCode Stats
        uses: KnlnKS/leetcode-stats@master
        with:
          username: getabalewKemaw
          github-token: ${{ secrets.GITHUB_TOKEN }}