name: Update LeetCode stats

on:
  schedule:
    - cron: '17 6 * * *' # daily at 06:17 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update README with LeetCode stats
        env:
          LEETCODE_USERNAME: getabalewkemaw
        run: node scripts/update-leetcode.mjs

      - name: Commit and push if changed
        run: |
          if ! git diff --quiet README.md; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update LeetCode stats"
            git push
          else
            echo "No changes to commit."
          fi
